### ISSUE TITLE
Version 1.6.0

### ISSUE THREAD

**Issue by restodo** [TodoPago/Plugin-VirtueMart#7]
Hola, buen día.
Instalé la última versión y el plugin mejoró muchisimo en prestaciones y opciones.
Al colocar una orden funciona todo bien, si el pago es confirmado al retornar a la tienda da error 400 Invalid Credentials.
Quiero aclarar que el pedido se registra bien en la base de datos, figura como Aprobada y en esta versión la consola aparece mostrando toda la información.
Si el pago no es confirmado por problema de tarjeta inválida o que la operación no pudo ser realizada en este momento, regresa al carrito y te permite realizar la operación nuevamente. Estaría bueno que muestre un mensaje al regresar al carrito indicando el problema porque de lo contrario el comprador no entiende cual fue el inconveniente.

Saludos!

**Comment by drarko** [comment]
@restodo buenas tardes.

¿Podrias adjuntarnos capturas de pantalla de estos comportamientos?
Por favor indicanos también, version de VirtueMart y de Joomla. 

Gracias

**Comment by restodo** [comment]
Gracias por la respuesta!
La versión de Joomla es 3.7.4 y de Virtuemart 3.2.2

Respecto a las capturas de pantalla, no son muy explícitas pero ahora te adjunto cuando completo el formulario de Todo Pago con datos para transacción aprobada.

![datos en formulario tp](https://user-images.githubusercontent.com/22160531/29181584-1fbbec90-7dd2-11e7-966f-1f4b12074a9b.png)
![error cuando vuelve a la tienda](https://user-images.githubusercontent.com/22160531/29181585-1fc04b1e-7dd2-11e7-86ec-24cca4cf8eed.png)

Esta es la ruta que aparece en el navegador cuando dar el error 400 Invalid Credentials.
http://test.restodo.com.ar/index.php?option=com_virtuemart&view=pluginresponse&task=pluginresponsereceived&on=201700269&pm=10&Answer=9fbc843b-7624-68b5-12d4-aab33dd0bea3

**Comment by restodo** [comment]
Luego hice la prueba colocando datos para "En este momento la operación no pudo ser realizada. Por favor intentá más tarde." y con el plugin configurado para Limpiar el carrito si el pago es rechazado "no habilitar"

![datos en formulario tp para no aprobar](https://user-images.githubusercontent.com/22160531/29181956-696e4ecc-7dd3-11e7-9689-6bde5315bd61.png)
![vuelve a la tienda sin problemas para intentar nuevamente pago](https://user-images.githubusercontent.com/22160531/29181960-6bf42658-7dd3-11e7-98a5-08c4114f38e8.png)

En el historial de ordenes guarda el pedido como Pendiente con datos correctos de todo el pedido, pero también genera una entrada en blanco con estado Cancelado

![orden pendiente](https://user-images.githubusercontent.com/22160531/29182022-9d245676-7dd3-11e7-9d78-43a8e756c23d.png)

**Comment by restodo** [comment]
Hice otra prueba colocando datos para "En este momento la operación no pudo ser realizada. Por favor intentá más tarde." y con el plugin configurado para Limpiar el carrito si el pago es rechazado "si habilitar"

![carrito vacio por no aprobar la operacion tp](https://user-images.githubusercontent.com/22160531/29182224-799b3552-7dd4-11e7-8cee-157b950bd938.png)

En el historial de ordenes guarda el pedido como Pendiente con datos correctos de todo el pedido, pero también genera una entrada en blanco con estado Cancelado

![esta de la orden en el historial](https://user-images.githubusercontent.com/22160531/29182228-7cd5491a-7dd4-11e7-8e21-8b9cb74cd028.png)

En este caso también estaría bueno que el plugin generara un Alert o un mensaje de error con el mensaje de porque no se pudo realizar el pago, porque sino el comprador no entiendo porque volvió a la tienda y se vació el carrito.

**Comment by restodo** [comment]
Te adjunto el log con los 3 ejemplos que te pasé, el primer bloque es cuando se aprueba el pago, el segundo cuando se cancela y vuelve al carrito y el último cuando se cancela y se vacía el carrito.

[todopago.0.log.php-ok.php.zip](https://github.com/TodoPago/Plugin-VirtueMart/files/1216785/todopago.0.log.php-ok.php.zip)

**Comment by restodo** [comment]
Hola @drarko pudiste ver la info solicitada? he intentado ver si puedo resolver el problema pero no encuentro que causa el error 400 Invalid Credentials en el archivo todopago.php

**Comment by restodo** [comment]
Hola @drarko @damianwajser estoy a la espera de que me comenten algo sobre el problema que existe con el plugin que subieron hace 1 semana aproximadamente.
Necesito hacer funcionarlo con el Virtuemart porque es lo único que me falta para pasar a producción la nueva tienda.
Estuve viendo que la variable $mb_data que existe en 2 funciones del archivo todopago.php no devuelve nada y por lo que vi debería traer información desde el sitio de todopago.

Quedo a la espera de sus comentarios.

**Comment by drarko** [comment]
Estimado.
Estamos revisando el caso con la información provista. A la brevedad estaremos informando novedades.

**Comment by restodo** [comment]
Gracias @drarko espero las novedades!

**Comment by restodo** [comment]
Hola @drarko @damianwajser quería saber si pudieron avanzar en la solución al problema?

**Comment by restodo** [comment]
Hola @drarko @damianwajser quería saber si pudieron avanzar en la solución al problema? Hace 20 días me comentaste que estaban revisando toda la información que les pasé hace casi 1 mes y me iban a informar a la brevedad pero 20 días y ninguna notica en la solución al problema.
Con que versión de Joomla y Virtuemart lo probaron ?

**Comment by restodo** [comment]
Hola @drarko @damianwajser paso 1 mes desde que me dijiste "A la brevedad estaremos informando novedades", fue una broma? Necesito poder implementar el plugin y que funcione por favor!

**Comment by restodo** [comment]
Hola @drarko  @damianwajser , hoy instalé la nueva versión que subieron pero me sigue ocurriendo el mismo error.
Al colocar una orden funciona todo bien, si el pago es confirmado al retornar a la tienda da error 400 Invalid Credentials.
Quiero aclarar que el pedido se registra bien en la base de datos, figura como Aprobada y en esta versión la consola aparece mostrando toda la información.
Me podrían dar una mano para poder implementar el sistema de cobro de Todo Pago ?

**Comment by josenovo77** [comment]
Hola Restodo, me esta ocurriendo lo mismo que a vos con todo pago, ¿encontraste la solucion ?

Saludos

**Comment by restodo** [comment]
Hola @josenovo77 , fijate los archivos que subí en el otro post que también creé para la versión 1.7.0
https://github.com/TodoPago/Plugin-VirtueMart/issues/9

**Comment by josenovo77** [comment]
Gracias por  responder, descargue e instale el archivo ahora no me genera el error  400 con visa y cabal (mastercard si), pero no se concretan las operaciones, son rechazadas, esto en modo produccion, en modo de desarrollo sigue con el error 400

**Comment by josenovo77** [comment]
Gracias, ahi lei bien los dos post, por lo que veo es un tema de mercadopago con falta de if, yo tengo el 2.0 (el 3.0 no funciona), por casualidad te acordad donde le faltaba las if?, asi no toqueteo de mas el archivo, ya lo estuve parchando bastante el archivo porque no funcionaba (no pasaba al español) y no quiero tocar algo incorrecto porque es una web funcional (en localhost no me funciona MP)
