### ISSUE TITLE
Version 1.7.0

### ISSUE THREAD

**Issue by restodo** [TodoPago/Plugin-VirtueMart#9]
Hola @drarko @damianwajser 
Instalé la última versión (1.7.0) para ver si habían solucionado el problema que reporte en el post titulado "Version 1.6.0" pero sigue exactamente igual, presenta la misma falla y a continuación se las vuelvo a repetir.
Al colocar una orden funciona todo bien, si el pago es confirmado al retornar a la tienda da error 400 Invalid Credentials.
Quiero aclarar que el pedido se registra bien en la base de datos, figura como Aprobada y en esta versión la consola aparece mostrando toda la información.
Si el pago no es confirmado por problema de tarjeta inválida o que la operación no pudo ser realizada en este momento, regresa al carrito y te permite realizar la operación nuevamente. 

El problema de la versión 1.6.0 lo reporte el 10 de Agosto, de que forma pueden analizar el problema? porque es imposible implementar el plugin pasando 3 meses y no tener solución por parte suya.

Si necesitan ver copias de pantalla las pueden ver en el post anterior. De igual forma sería bueno que aclaren con que versión de Joomla / Virtuemart realizaron las pruebas y les funcionó el plugin.

Quedo a la espera de sus comentarios!

**Comment by alejandro021987** [comment]
Que tal @restodo, ¿pudiste solucionar este inconveniente?.  Hicimos pruebas con VirtueMart 3.0.18, Joomla version 3.6.2 y funciono sin problemas. Saludos!

**Comment by restodo** [comment]
Hola @alejandro021987, desde que cree este ticket sigue el mismo inconveniente. No pude implementar el plugin en Virtuemart. Nosotros tenemos Joomla 3.8.2 y Virtuemart 3.2.4
Es muy vieja la versión de Virtuemart que están utilizando, salió en Septiembre del 2016. Si tenés posibilidad actualizá a mis versiones o incluso ya hay nuevas (Joomla 3.8.3 y Virtuemart 3.2.12) y luego de hacer las pruebas con esas versiones me avisas si no te devuelve el error que comento. Seguramente ahí puedan solucionar el inconveniente porque desde la versión 3.0.18 de VM cambió mucho.

Quedo a la espera de tus comentarios!

**Comment by alejandro021987** [comment]
Que tal @restodo, te queria avisar que ya hicimos las pruebas con Joomla 3.8.2 y Virtuemart 3.2.4 y estan funcionando correctamente. Por lo que comentabas, el tipo de error que te aparece que dice "Invalid Credentials" lo podes solucionar regenerando las credenciales desde todopago.com.ar -> Soluciones para vendedores -> integracion avanzada.  
Ahí podes regenerar tanto para "Ambiente de producción" como para "Ambiente de pruebas".
Saludos

**Comment by restodo** [comment]
@alejandro021987 gracias por la pronta respuesta, el mensaje de error Invalid Credentials me aparece al regresar del formulario de Todo Pago al Virtuemart. Si fuera un problema de las credenciales del ambiente de prueba no me permitiría llegar al formulario, colocar todos los datos de la tarjeta de prueba y que la operación quede registrada tanto en la cuenta de prueba de Todo Pago como en la base de datos del Virtuemart.
Si hiciste la prueba con Joomla 3.8.2 y Virtuemart 3.2.4, este fin de semana voy a instalar un sistema en blanco de esas 2 versiones y probar la versión 1.7.0 nuevamente pero no creo que sea ese el problema.
Tengo una duda que quizas podés aclararme, mi hosting es Linux pero confirmo que en la configuración de php tengo habilitadas php_soap y php_openssl pero al ser Linux no son dll. Puede ser eso un problema?

**Comment by restodo** [comment]
@alejandro021987 hay alguna forma de probar si esos paquetes funcionan bien para el plugin de Todo Pago ?

**Comment by alejandro021987** [comment]
Hola @restodo, dale tratá de instalar uno desde cero y trata de instalarte un paquete que sea full_package  asi no tenes que andar instalando por separado los modulos para armar el ecommerce. El php_soap debe estar habilitado ya que sino no abriría el formulario. De todas formas para ver si estan instalados podes hacer un phpinfo() en algun archivo y ver si estan habilitados los modulos necesarios. Si aun falta alguno debes instalarlos por consola y luego habilitarlos desde el php ini.
saludos

**Comment by restodo** [comment]
Hola @alejandro021987 , luego de instalar un entorno completamente nuevo (full package) y solo el plugin de Todo Pago pude hacer un pago correctamente.
Para descubrir cual es el problema que ocurre en mi página usando el plugin de Todo Pago, fui instalando uno a uno los otros plugins y componentes que tengo actualmente hasta que detecté cual es el que causa el problema de error 400 Invalid Credentials.
Por alguna razón que no pude descubrir si tengo instalado el plugin de Todo Pago y Mercadopago , al hacer un pago con Todo Pago devuelve error 400 Invalid Credentials. Si desinstalo el plugin de Mercadopago puedo hacer el pago correctamente. 
Pienso que hay algun problem en el plugin de Todo Pago porque si tengo los 2 plugins (TP y MP) e intento realizar un pago con Mercadopago funciona correctamente.

Si querés reproducir el problema te estoy adjunto el plugin de Mercadopago. Con solo instalarlo y habilitar el plugin vas a poder ver el error 400 Invalid Credentials cuando hagas un pago con Todo Pago.

[MP-virtuemart-v2.0.7.zip](https://github.com/TodoPago/Plugin-VirtueMart/files/1594688/MP-virtuemart-v2.0.7.zip)

**Comment by restodo** [comment]
Hola @alejandro021987 , pude solucionar el problema que te comenté en el último post. Lo causaba el plugin de Mercadopago porque le faltaban algunos If y por esa razón cuando volvía del formulario de Todo Pago tomaba el de Mercadopago.
Te adjunto el archivo todopago.php que tiene algunas modificaciones para que por ejemplo muestre el nombre del método de pago, en este caso Todo Pago, en el mail y en el detalle del pedido en la cuenta. Por otro lado vas a ver algunas modificaciones que están marcadas como // - RS - .....

Luego de hacer todas las pruebas funciona perfecto, solo encontré el siguiente problema cuando hago una prueba con una tarjeta que devuelve 99955 o 99997.
Cuando ocurre alguno de los 2 casos que te comento, en la lista de pedidos aparece uno Pendiente con todo el detalle del pedido + producto y una entrada sin número de pedido. Te adjunto las imágenes de los 2 casos.

Entiendo que si ocurren alguno de los casos 99955 o 99997, como vuelve al carrito y te permite intentar hacer nuevamente el pago, no se debería crear una entrada de pedido. 
A lo sumo debería crear una entrada de pedido Cancelado cuando está seleccionado limpiar el carrito con pago rechazado pero tampoco ocurre, se repite lo mismo que con 99955 o 99997.

Quedo a la espera de tus comentarios.

Saludos!!
![99955 - la tarjeta ingresada es invalida](https://user-images.githubusercontent.com/22160531/34507107-d8072a56-f011-11e7-98f4-1d416a6d464c.png)
![99997 - en este momento la operacion no pudo ser realizada](https://user-images.githubusercontent.com/22160531/34507108-d82c3288-f011-11e7-8746-310cbdf67079.png)
[todopago.zip](https://github.com/TodoPago/Plugin-VirtueMart/files/1599243/todopago.zip)

**Comment by restodo** [comment]
Hola @alejandro021987 , pude solucionar el problema de la generación de una orden sin número cuando el pago es realizado con una tarjeta que devuelve 99955 o 99997.
Modifiqué algunas cosas en la función plgVmOnUserPaymentCancel ()

Te adjunto el archivo todopago.php para que le des un vistazo y lo pruebes así analizas si lo subis al productivo.

No pude ver si funciona el reintegro de dinero desde el pedido en si porque me devuelve un error que no lo puede realizar por no tener las comisiones, entiendo que debe ocurrir porque la cuenta es de developer y no la productiva.

Intenté ingresar al historial de operaciones de la cuenta developer pero me da un error por lo que no puede intentar realizar una devolución por ahí y ver si cambia el estado. Me podés decir si está funcionando mal la web?

[todopago.zip](https://github.com/TodoPago/Plugin-VirtueMart/files/1602287/todopago.zip)
